version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.front
    image: bigcam-frontend
    ports:
      - "8080:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: dockerfile.backend
    image: bigcam-server
    ports:
      - "3000:3000"