networks:
  dev:

services:

  frontend:
    build: 
      context: ../FitnessMonitor_Frontend
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - dev
    