networks:
  dev:


services:
  backend:
    build: ./backend
    networks:
      - dev

  frontend:
    build: ./frontend
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    